<?php

use Illuminate\Database\Seeder;
use App\Policestation;

class PoliceStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
Policestation::create(["id"=>"1","district_id"=>"34","name"=>"Amtali","bn_name"=>"আমতলী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"2","district_id"=>"34","name"=>"Bamna ","bn_name"=>"বামনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"3","district_id"=>"34","name"=>"Barguna Sadar ","bn_name"=>"বরগুনা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"4","district_id"=>"34","name"=>"Betagi ","bn_name"=>"বেতাগি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"5","district_id"=>"34","name"=>"Patharghata ","bn_name"=>"পাথরঘাটা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"6","district_id"=>"34","name"=>"Taltali ","bn_name"=>"তালতলী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"7","district_id"=>"35","name"=>"Muladi ","bn_name"=>"মুলাদি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"8","district_id"=>"35","name"=>"Babuganj ","bn_name"=>"বাবুগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"9","district_id"=>"35","name"=>"Agailjhara ","bn_name"=>"আগাইলঝরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"10","district_id"=>"35","name"=>"Barisal Sadar ","bn_name"=>"বরিশাল সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"11","district_id"=>"35","name"=>"Bakerganj ","bn_name"=>"বাকেরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"12","district_id"=>"35","name"=>"Banaripara ","bn_name"=>"বানাড়িপারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"13","district_id"=>"35","name"=>"Gaurnadi ","bn_name"=>"গৌরনদী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"14","district_id"=>"35","name"=>"Hizla ","bn_name"=>"হিজলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"15","district_id"=>"35","name"=>"Mehendiganj ","bn_name"=>"মেহেদিগঞ্জ ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"16","district_id"=>"35","name"=>"Wazirpur ","bn_name"=>"ওয়াজিরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"17","district_id"=>"36","name"=>"Bhola Sadar ","bn_name"=>"ভোলা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"18","district_id"=>"36","name"=>"Burhanuddin ","bn_name"=>"বুরহানউদ্দিন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"19","district_id"=>"36","name"=>"Char Fasson ","bn_name"=>"চর ফ্যাশন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"20","district_id"=>"36","name"=>"Daulatkhan ","bn_name"=>"দৌলতখান","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"21","district_id"=>"36","name"=>"Lalmohan ","bn_name"=>"লালমোহন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"22","district_id"=>"36","name"=>"Manpura ","bn_name"=>"মনপুরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"23","district_id"=>"36","name"=>"Tazumuddin ","bn_name"=>"তাজুমুদ্দিন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"24","district_id"=>"37","name"=>"Jhalokati Sadar ","bn_name"=>"ঝালকাঠি সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"25","district_id"=>"37","name"=>"Kathalia ","bn_name"=>"কাঁঠালিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"26","district_id"=>"37","name"=>"Nalchity ","bn_name"=>"নালচিতি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"27","district_id"=>"37","name"=>"Rajapur ","bn_name"=>"রাজাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"28","district_id"=>"38","name"=>"Bauphal ","bn_name"=>"বাউফল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"29","district_id"=>"38","name"=>"Dashmina ","bn_name"=>"দশমিনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"30","district_id"=>"38","name"=>"Galachipa ","bn_name"=>"গলাচিপা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"31","district_id"=>"38","name"=>"Kalapara ","bn_name"=>"কালাপারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"32","district_id"=>"38","name"=>"Mirzaganj ","bn_name"=>"মির্জাগঞ্জ ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"33","district_id"=>"38","name"=>"Patuakhali Sadar ","bn_name"=>"পটুয়াখালী সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"34","district_id"=>"38","name"=>"Dumki ","bn_name"=>"ডুমকি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"35","district_id"=>"38","name"=>"Rangabali ","bn_name"=>"রাঙ্গাবালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"36","district_id"=>"39","name"=>"Bhandaria","bn_name"=>"ভ্যান্ডারিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"37","district_id"=>"39","name"=>"Kaukhali","bn_name"=>"কাউখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"38","district_id"=>"39","name"=>"Mathbaria","bn_name"=>"মাঠবাড়িয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"39","district_id"=>"39","name"=>"Nazirpur","bn_name"=>"নাজিরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"40","district_id"=>"39","name"=>"Nesarabad","bn_name"=>"নেসারাবাদ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"41","district_id"=>"39","name"=>"Pirojpur Sadar","bn_name"=>"পিরোজপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"42","district_id"=>"39","name"=>"Zianagar","bn_name"=>"জিয়ানগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"43","district_id"=>"40","name"=>"Bandarban Sadar","bn_name"=>"বান্দরবন সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"44","district_id"=>"40","name"=>"Thanchi","bn_name"=>"থানচি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"45","district_id"=>"40","name"=>"Lama","bn_name"=>"লামা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"46","district_id"=>"40","name"=>"Naikhongchhari","bn_name"=>"নাইখংছড়ি ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"47","district_id"=>"40","name"=>"Ali kadam","bn_name"=>"আলী কদম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"48","district_id"=>"40","name"=>"Rowangchhari","bn_name"=>"রউয়াংছড়ি ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"49","district_id"=>"40","name"=>"Ruma","bn_name"=>"রুমা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"50","district_id"=>"41","name"=>"Brahmanbaria Sadar ","bn_name"=>"ব্রাহ্মণবাড়িয়া সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"51","district_id"=>"41","name"=>"Ashuganj ","bn_name"=>"আশুগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"52","district_id"=>"41","name"=>"Nasirnagar ","bn_name"=>"নাসির নগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"53","district_id"=>"41","name"=>"Nabinagar ","bn_name"=>"নবীনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"54","district_id"=>"41","name"=>"Sarail ","bn_name"=>"সরাইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"55","district_id"=>"41","name"=>"Shahbazpur Town","bn_name"=>"শাহবাজপুর টাউন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"56","district_id"=>"41","name"=>"Kasba ","bn_name"=>"কসবা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"57","district_id"=>"41","name"=>"Akhaura ","bn_name"=>"আখাউরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"58","district_id"=>"41","name"=>"Bancharampur ","bn_name"=>"বাঞ্ছারামপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"59","district_id"=>"41","name"=>"Bijoynagar ","bn_name"=>"বিজয় নগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"60","district_id"=>"42","name"=>"Chandpur Sadar","bn_name"=>"চাঁদপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"61","district_id"=>"42","name"=>"Faridganj","bn_name"=>"ফরিদগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"62","district_id"=>"42","name"=>"Haimchar","bn_name"=>"হাইমচর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"63","district_id"=>"42","name"=>"Haziganj","bn_name"=>"হাজীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"64","district_id"=>"42","name"=>"Kachua","bn_name"=>"কচুয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"65","district_id"=>"42","name"=>"Matlab Uttar","bn_name"=>"মতলব উত্তর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"66","district_id"=>"42","name"=>"Matlab Dakkhin","bn_name"=>"মতলব দক্ষিণ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"67","district_id"=>"42","name"=>"Shahrasti","bn_name"=>"শাহরাস্তি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"68","district_id"=>"43","name"=>"Anwara ","bn_name"=>"আনোয়ারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"69","district_id"=>"43","name"=>"Banshkhali ","bn_name"=>"বাশখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"70","district_id"=>"43","name"=>"Boalkhali ","bn_name"=>"বোয়ালখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"71","district_id"=>"43","name"=>"Chandanaish ","bn_name"=>"চন্দনাইশ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"72","district_id"=>"43","name"=>"Fatikchhari ","bn_name"=>"ফটিকছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"73","district_id"=>"43","name"=>"Hathazari ","bn_name"=>"হাঠহাজারী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"74","district_id"=>"43","name"=>"Lohagara ","bn_name"=>"লোহাগারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"75","district_id"=>"43","name"=>"Mirsharai ","bn_name"=>"মিরসরাই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"76","district_id"=>"43","name"=>"Patiya ","bn_name"=>"পটিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"77","district_id"=>"43","name"=>"Rangunia ","bn_name"=>"রাঙ্গুনিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"78","district_id"=>"43","name"=>"Raozan ","bn_name"=>"রাউজান","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"79","district_id"=>"43","name"=>"Sandwip ","bn_name"=>"সন্দ্বীপ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"80","district_id"=>"43","name"=>"Satkania ","bn_name"=>"সাতকানিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"81","district_id"=>"43","name"=>"Sitakunda ","bn_name"=>"সীতাকুণ্ড","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"82","district_id"=>"44","name"=>"Barura ","bn_name"=>"বড়ুরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"83","district_id"=>"44","name"=>"Brahmanpara ","bn_name"=>"ব্রাহ্মণপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"84","district_id"=>"44","name"=>"Burichong ","bn_name"=>"বুড়িচং","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"85","district_id"=>"44","name"=>"Chandina ","bn_name"=>"চান্দিনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"86","district_id"=>"44","name"=>"Chauddagram ","bn_name"=>"চৌদ্দগ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"87","district_id"=>"44","name"=>"Daudkandi ","bn_name"=>"দাউদকান্দি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"88","district_id"=>"44","name"=>"Debidwar ","bn_name"=>"দেবীদ্বার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"89","district_id"=>"44","name"=>"Homna ","bn_name"=>"হোমনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"90","district_id"=>"44","name"=>"Comilla Sadar ","bn_name"=>"কুমিল্লা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"91","district_id"=>"44","name"=>"Laksam ","bn_name"=>"লাকসাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"92","district_id"=>"44","name"=>"Monohorgonj ","bn_name"=>"মনোহরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"93","district_id"=>"44","name"=>"Meghna ","bn_name"=>"মেঘনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"94","district_id"=>"44","name"=>"Muradnagar ","bn_name"=>"মুরাদনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"95","district_id"=>"44","name"=>"Nangalkot ","bn_name"=>"নাঙ্গালকোট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"96","district_id"=>"44","name"=>"Comilla Sadar South ","bn_name"=>"কুমিল্লা সদর দক্ষিণ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"97","district_id"=>"44","name"=>"Titas ","bn_name"=>"তিতাস","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"98","district_id"=>"45","name"=>"Chakaria ","bn_name"=>"চকরিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"99","district_id"=>"45","name"=>"Chakaria ","bn_name"=>"চকরিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"100","district_id"=>"45","name"=>"Cox's Bazar Sadar ","bn_name"=>"কক্স বাজার সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"101","district_id"=>"45","name"=>"Kutubdia ","bn_name"=>"কুতুবদিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"102","district_id"=>"45","name"=>"Maheshkhali ","bn_name"=>"মহেশখালী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"103","district_id"=>"45","name"=>"Ramu ","bn_name"=>"রামু","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"104","district_id"=>"45","name"=>"Teknaf ","bn_name"=>"টেকনাফ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"105","district_id"=>"45","name"=>"Ukhia ","bn_name"=>"উখিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"106","district_id"=>"45","name"=>"Pekua ","bn_name"=>"পেকুয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"107","district_id"=>"46","name"=>"Feni Sadar","bn_name"=>"ফেনী সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"108","district_id"=>"46","name"=>"Chagalnaiya","bn_name"=>"ছাগল নাইয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"109","district_id"=>"46","name"=>"Daganbhyan","bn_name"=>"দাগানভিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"110","district_id"=>"46","name"=>"Parshuram","bn_name"=>"পরশুরাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"111","district_id"=>"46","name"=>"Fhulgazi","bn_name"=>"ফুলগাজি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"112","district_id"=>"46","name"=>"Sonagazi","bn_name"=>"সোনাগাজি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"113","district_id"=>"47","name"=>"Dighinala ","bn_name"=>"দিঘিনালা ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"114","district_id"=>"47","name"=>"Khagrachhari ","bn_name"=>"খাগড়াছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"115","district_id"=>"47","name"=>"Lakshmichhari ","bn_name"=>"লক্ষ্মীছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"116","district_id"=>"47","name"=>"Mahalchhari ","bn_name"=>"মহলছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"117","district_id"=>"47","name"=>"Manikchhari ","bn_name"=>"মানিকছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"118","district_id"=>"47","name"=>"Matiranga ","bn_name"=>"মাটিরাঙ্গা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"119","district_id"=>"47","name"=>"Panchhari ","bn_name"=>"পানছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"120","district_id"=>"47","name"=>"Ramgarh ","bn_name"=>"রামগড়","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"121","district_id"=>"48","name"=>"Lakshmipur Sadar ","bn_name"=>"লক্ষ্মীপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"122","district_id"=>"48","name"=>"Raipur ","bn_name"=>"রায়পুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"123","district_id"=>"48","name"=>"Ramganj ","bn_name"=>"রামগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"124","district_id"=>"48","name"=>"Ramgati ","bn_name"=>"রামগতি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"125","district_id"=>"48","name"=>"Komol Nagar ","bn_name"=>"কমল নগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"126","district_id"=>"49","name"=>"Noakhali Sadar ","bn_name"=>"নোয়াখালী সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"127","district_id"=>"49","name"=>"Begumganj ","bn_name"=>"বেগমগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"128","district_id"=>"49","name"=>"Chatkhil ","bn_name"=>"চাটখিল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"129","district_id"=>"49","name"=>"Companyganj ","bn_name"=>"কোম্পানীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"130","district_id"=>"49","name"=>"Shenbag ","bn_name"=>"শেনবাগ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"131","district_id"=>"49","name"=>"Hatia ","bn_name"=>"হাতিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"132","district_id"=>"49","name"=>"Kobirhat ","bn_name"=>"কবিরহাট ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"133","district_id"=>"49","name"=>"Sonaimuri ","bn_name"=>"সোনাইমুরি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"134","district_id"=>"49","name"=>"Suborno Char ","bn_name"=>"সুবর্ণ চর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"135","district_id"=>"50","name"=>"Rangamati Sadar ","bn_name"=>"রাঙ্গামাটি সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"136","district_id"=>"50","name"=>"Belaichhari ","bn_name"=>"বেলাইছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"137","district_id"=>"50","name"=>"Bagaichhari ","bn_name"=>"বাঘাইছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"138","district_id"=>"50","name"=>"Barkal ","bn_name"=>"বরকল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"139","district_id"=>"50","name"=>"Juraichhari ","bn_name"=>"জুরাইছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"140","district_id"=>"50","name"=>"Rajasthali ","bn_name"=>"রাজাস্থলি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"141","district_id"=>"50","name"=>"Kaptai ","bn_name"=>"কাপ্তাই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"142","district_id"=>"50","name"=>"Langadu ","bn_name"=>"লাঙ্গাডু","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"143","district_id"=>"50","name"=>"Nannerchar ","bn_name"=>"নান্নেরচর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"144","district_id"=>"50","name"=>"Kaukhali ","bn_name"=>"কাউখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"150","district_id"=>"2","name"=>"Faridpur Sadar ","bn_name"=>"ফরিদপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"151","district_id"=>"2","name"=>"Boalmari ","bn_name"=>"বোয়ালমারী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"152","district_id"=>"2","name"=>"Alfadanga ","bn_name"=>"আলফাডাঙ্গা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"153","district_id"=>"2","name"=>"Madhukhali ","bn_name"=>"মধুখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"154","district_id"=>"2","name"=>"Bhanga ","bn_name"=>"ভাঙ্গা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"155","district_id"=>"2","name"=>"Nagarkanda ","bn_name"=>"নগরকান্ড","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"156","district_id"=>"2","name"=>"Charbhadrasan ","bn_name"=>"চরভদ্রাসন ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"157","district_id"=>"2","name"=>"Sadarpur ","bn_name"=>"সদরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"158","district_id"=>"2","name"=>"Shaltha ","bn_name"=>"শালথা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"159","district_id"=>"3","name"=>"Gazipur Sadar-Joydebpur","bn_name"=>"গাজীপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"160","district_id"=>"3","name"=>"Kaliakior","bn_name"=>"কালিয়াকৈর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"161","district_id"=>"3","name"=>"Kapasia","bn_name"=>"কাপাসিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"162","district_id"=>"3","name"=>"Sripur","bn_name"=>"শ্রীপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"163","district_id"=>"3","name"=>"Kaliganj","bn_name"=>"কালীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"164","district_id"=>"3","name"=>"Tongi","bn_name"=>"টঙ্গি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"165","district_id"=>"4","name"=>"Gopalganj Sadar ","bn_name"=>"গোপালগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"166","district_id"=>"4","name"=>"Kashiani ","bn_name"=>"কাশিয়ানি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"167","district_id"=>"4","name"=>"Kotalipara ","bn_name"=>"কোটালিপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"168","district_id"=>"4","name"=>"Muksudpur ","bn_name"=>"মুকসুদপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"169","district_id"=>"4","name"=>"Tungipara ","bn_name"=>"টুঙ্গিপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"170","district_id"=>"5","name"=>"Dewanganj ","bn_name"=>"দেওয়ানগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"171","district_id"=>"5","name"=>"Baksiganj ","bn_name"=>"বকসিগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"172","district_id"=>"5","name"=>"Islampur ","bn_name"=>"ইসলামপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"173","district_id"=>"5","name"=>"Jamalpur Sadar ","bn_name"=>"জামালপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"174","district_id"=>"5","name"=>"Madarganj ","bn_name"=>"মাদারগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"175","district_id"=>"5","name"=>"Melandaha ","bn_name"=>"মেলানদাহা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"176","district_id"=>"5","name"=>"Sarishabari ","bn_name"=>"সরিষাবাড়ি ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"177","district_id"=>"5","name"=>"Narundi Police I.C","bn_name"=>"নারুন্দি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"178","district_id"=>"6","name"=>"Astagram ","bn_name"=>"অষ্টগ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"179","district_id"=>"6","name"=>"Bajitpur ","bn_name"=>"বাজিতপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"180","district_id"=>"6","name"=>"Bhairab ","bn_name"=>"ভৈরব","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"181","district_id"=>"6","name"=>"Hossainpur ","bn_name"=>"হোসেনপুর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"182","district_id"=>"6","name"=>"Itna ","bn_name"=>"ইটনা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"183","district_id"=>"6","name"=>"Karimganj ","bn_name"=>"করিমগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"184","district_id"=>"6","name"=>"Katiadi ","bn_name"=>"কতিয়াদি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"185","district_id"=>"6","name"=>"Kishoreganj Sadar ","bn_name"=>"কিশোরগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"186","district_id"=>"6","name"=>"Kuliarchar ","bn_name"=>"কুলিয়ারচর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"187","district_id"=>"6","name"=>"Mithamain ","bn_name"=>"মিঠামাইন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"188","district_id"=>"6","name"=>"Nikli ","bn_name"=>"নিকলি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"189","district_id"=>"6","name"=>"Pakundia ","bn_name"=>"পাকুন্ডা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"190","district_id"=>"6","name"=>"Tarail ","bn_name"=>"তাড়াইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"191","district_id"=>"7","name"=>"Madaripur Sadar","bn_name"=>"মাদারীপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"192","district_id"=>"7","name"=>"Kalkini","bn_name"=>"কালকিনি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"193","district_id"=>"7","name"=>"Rajoir","bn_name"=>"রাজইর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"194","district_id"=>"7","name"=>"Shibchar","bn_name"=>"শিবচর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"195","district_id"=>"8","name"=>"Manikganj Sadar ","bn_name"=>"মানিকগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"196","district_id"=>"8","name"=>"Singair ","bn_name"=>"সিঙ্গাইর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"197","district_id"=>"8","name"=>"Shibalaya ","bn_name"=>"শিবালয়","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"198","district_id"=>"8","name"=>"Saturia ","bn_name"=>"সাঠুরিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"199","district_id"=>"8","name"=>"Harirampur ","bn_name"=>"হরিরামপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"200","district_id"=>"8","name"=>"Ghior ","bn_name"=>"ঘিওর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"201","district_id"=>"8","name"=>"Daulatpur ","bn_name"=>"দৌলতপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"202","district_id"=>"9","name"=>"Lohajang ","bn_name"=>"লোহাজং","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"203","district_id"=>"9","name"=>"Sreenagar ","bn_name"=>"শ্রীনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"204","district_id"=>"9","name"=>"Munshiganj Sadar ","bn_name"=>"মুন্সিগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"205","district_id"=>"9","name"=>"Sirajdikhan ","bn_name"=>"সিরাজদিখান","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"206","district_id"=>"9","name"=>"Tongibari ","bn_name"=>"টঙ্গিবাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"207","district_id"=>"9","name"=>"Gazaria ","bn_name"=>"গজারিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"208","district_id"=>"10","name"=>"Bhaluka","bn_name"=>"ভালুকা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"209","district_id"=>"10","name"=>"Trishal","bn_name"=>"ত্রিশাল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"210","district_id"=>"10","name"=>"Haluaghat","bn_name"=>"হালুয়াঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"211","district_id"=>"10","name"=>"Muktagachha","bn_name"=>"মুক্তাগাছা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"212","district_id"=>"10","name"=>"Dhobaura","bn_name"=>"ধবারুয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"213","district_id"=>"10","name"=>"Fulbaria","bn_name"=>"ফুলবাড়িয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"214","district_id"=>"10","name"=>"Gaffargaon","bn_name"=>"গফরগাঁও","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"215","district_id"=>"10","name"=>"Gauripur","bn_name"=>"গৌরিপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"216","district_id"=>"10","name"=>"Ishwarganj","bn_name"=>"ঈশ্বরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"217","district_id"=>"10","name"=>"Mymensingh Sadar","bn_name"=>"ময়মনসিং সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"218","district_id"=>"10","name"=>"Nandail","bn_name"=>"নন্দাইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"219","district_id"=>"10","name"=>"Phulpur","bn_name"=>"ফুলপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"220","district_id"=>"11","name"=>"Araihazar ","bn_name"=>"আড়াইহাজার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"221","district_id"=>"11","name"=>"Sonargaon ","bn_name"=>"সোনারগাঁও","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"222","district_id"=>"11","name"=>"Bandar","bn_name"=>"বান্দার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"223","district_id"=>"11","name"=>"Naryanganj Sadar ","bn_name"=>"নারায়ানগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"224","district_id"=>"11","name"=>"Rupganj ","bn_name"=>"রূপগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"225","district_id"=>"11","name"=>"Siddirgonj ","bn_name"=>"সিদ্ধিরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"226","district_id"=>"12","name"=>"Belabo ","bn_name"=>"বেলাবো","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"227","district_id"=>"12","name"=>"Monohardi ","bn_name"=>"মনোহরদি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"228","district_id"=>"12","name"=>"Narsingdi Sadar ","bn_name"=>"নরসিংদী সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"229","district_id"=>"12","name"=>"Palash ","bn_name"=>"পলাশ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"230","district_id"=>"12","name"=>"Raipura , Narsingdi","bn_name"=>"রায়পুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"231","district_id"=>"12","name"=>"Shibpur ","bn_name"=>"শিবপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"232","district_id"=>"13","name"=>"Kendua Upazilla","bn_name"=>"কেন্দুয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"233","district_id"=>"13","name"=>"Atpara Upazilla","bn_name"=>"আটপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"234","district_id"=>"13","name"=>"Barhatta Upazilla","bn_name"=>"বরহাট্টা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"235","district_id"=>"13","name"=>"Durgapur Upazilla","bn_name"=>"দুর্গাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"236","district_id"=>"13","name"=>"Kalmakanda Upazilla","bn_name"=>"কলমাকান্দা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"237","district_id"=>"13","name"=>"Madan Upazilla","bn_name"=>"মদন","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"238","district_id"=>"13","name"=>"Mohanganj Upazilla","bn_name"=>"মোহনগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"239","district_id"=>"13","name"=>"Netrakona-S Upazilla","bn_name"=>"নেত্রকোনা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"240","district_id"=>"13","name"=>"Purbadhala Upazilla","bn_name"=>"পূর্বধলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"241","district_id"=>"13","name"=>"Khaliajuri Upazilla","bn_name"=>"খালিয়াজুরি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"242","district_id"=>"14","name"=>"Baliakandi ","bn_name"=>"বালিয়াকান্দি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"243","district_id"=>"14","name"=>"Goalandaghat ","bn_name"=>"গোয়ালন্দ ঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"244","district_id"=>"14","name"=>"Pangsha ","bn_name"=>"পাংশা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"245","district_id"=>"14","name"=>"Kalukhali ","bn_name"=>"কালুখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"246","district_id"=>"14","name"=>"Rajbari Sadar ","bn_name"=>"রাজবাড়ি সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"247","district_id"=>"15","name"=>"Shariatpur Sadar -Palong","bn_name"=>"শরীয়তপুর সদর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"248","district_id"=>"15","name"=>"Damudya ","bn_name"=>"দামুদিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"249","district_id"=>"15","name"=>"Naria ","bn_name"=>"নড়িয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"250","district_id"=>"15","name"=>"Jajira ","bn_name"=>"জাজিরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"251","district_id"=>"15","name"=>"Bhedarganj ","bn_name"=>"ভেদারগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"252","district_id"=>"15","name"=>"Gosairhat ","bn_name"=>"গোসাইর হাট ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"253","district_id"=>"16","name"=>"Jhenaigati ","bn_name"=>"ঝিনাইগাতি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"254","district_id"=>"16","name"=>"Nakla ","bn_name"=>"নাকলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"255","district_id"=>"16","name"=>"Nalitabari ","bn_name"=>"নালিতাবাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"256","district_id"=>"16","name"=>"Sherpur Sadar ","bn_name"=>"শেরপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"257","district_id"=>"16","name"=>"Sreebardi ","bn_name"=>"শ্রীবরদি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"258","district_id"=>"17","name"=>"Tangail Sadar ","bn_name"=>"টাঙ্গাইল সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"259","district_id"=>"17","name"=>"Sakhipur ","bn_name"=>"সখিপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"260","district_id"=>"17","name"=>"Basail ","bn_name"=>"বসাইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"261","district_id"=>"17","name"=>"Madhupur ","bn_name"=>"মধুপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"262","district_id"=>"17","name"=>"Ghatail ","bn_name"=>"ঘাটাইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"263","district_id"=>"17","name"=>"Kalihati ","bn_name"=>"কালিহাতি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"264","district_id"=>"17","name"=>"Nagarpur ","bn_name"=>"নগরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"265","district_id"=>"17","name"=>"Mirzapur ","bn_name"=>"মির্জাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"266","district_id"=>"17","name"=>"Gopalpur ","bn_name"=>"গোপালপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"267","district_id"=>"17","name"=>"Delduar ","bn_name"=>"দেলদুয়ার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"268","district_id"=>"17","name"=>"Bhuapur ","bn_name"=>"ভুয়াপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"269","district_id"=>"17","name"=>"Dhanbari ","bn_name"=>"ধানবাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"270","district_id"=>"55","name"=>"Bagerhat Sadar ","bn_name"=>"বাগেরহাট সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"271","district_id"=>"55","name"=>"Chitalmari ","bn_name"=>"চিতলমাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"272","district_id"=>"55","name"=>"Fakirhat ","bn_name"=>"ফকিরহাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"273","district_id"=>"55","name"=>"Kachua ","bn_name"=>"কচুয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"274","district_id"=>"55","name"=>"Mollahat ","bn_name"=>"মোল্লাহাট ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"275","district_id"=>"55","name"=>"Mongla ","bn_name"=>"মংলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"276","district_id"=>"55","name"=>"Morrelganj ","bn_name"=>"মরেলগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"277","district_id"=>"55","name"=>"Rampal ","bn_name"=>"রামপাল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"278","district_id"=>"55","name"=>"Sarankhola ","bn_name"=>"স্মরণখোলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"279","district_id"=>"56","name"=>"Damurhuda ","bn_name"=>"দামুরহুদা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"280","district_id"=>"56","name"=>"Chuadanga-S ","bn_name"=>"চুয়াডাঙ্গা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"281","district_id"=>"56","name"=>"Jibannagar ","bn_name"=>"জীবন নগর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"282","district_id"=>"56","name"=>"Alamdanga ","bn_name"=>"আলমডাঙ্গা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"283","district_id"=>"57","name"=>"Abhaynagar ","bn_name"=>"অভয়নগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"284","district_id"=>"57","name"=>"Keshabpur ","bn_name"=>"কেশবপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"285","district_id"=>"57","name"=>"Bagherpara ","bn_name"=>"বাঘের পাড়া ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"286","district_id"=>"57","name"=>"Jessore Sadar ","bn_name"=>"যশোর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"287","district_id"=>"57","name"=>"Chaugachha ","bn_name"=>"চৌগাছা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"288","district_id"=>"57","name"=>"Manirampur ","bn_name"=>"মনিরামপুর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"289","district_id"=>"57","name"=>"Jhikargachha ","bn_name"=>"ঝিকরগাছা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"290","district_id"=>"57","name"=>"Sharsha ","bn_name"=>"সারশা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"291","district_id"=>"58","name"=>"Jhenaidah Sadar ","bn_name"=>"ঝিনাইদহ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"292","district_id"=>"58","name"=>"Maheshpur ","bn_name"=>"মহেশপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"293","district_id"=>"58","name"=>"Kaliganj ","bn_name"=>"কালীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"294","district_id"=>"58","name"=>"Kotchandpur ","bn_name"=>"কোট চাঁদপুর ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"295","district_id"=>"58","name"=>"Shailkupa ","bn_name"=>"শৈলকুপা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"296","district_id"=>"58","name"=>"Harinakunda ","bn_name"=>"হাড়িনাকুন্দা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"297","district_id"=>"59","name"=>"Terokhada ","bn_name"=>"তেরোখাদা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"298","district_id"=>"59","name"=>"Batiaghata ","bn_name"=>"বাটিয়াঘাটা ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"299","district_id"=>"59","name"=>"Dacope ","bn_name"=>"ডাকপে","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"300","district_id"=>"59","name"=>"Dumuria ","bn_name"=>"ডুমুরিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"301","district_id"=>"59","name"=>"Dighalia ","bn_name"=>"দিঘলিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"302","district_id"=>"59","name"=>"Koyra ","bn_name"=>"কয়ড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"303","district_id"=>"59","name"=>"Paikgachha ","bn_name"=>"পাইকগাছা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"304","district_id"=>"59","name"=>"Phultala ","bn_name"=>"ফুলতলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"305","district_id"=>"59","name"=>"Rupsa ","bn_name"=>"রূপসা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"306","district_id"=>"60","name"=>"Kushtia Sadar","bn_name"=>"কুষ্টিয়া সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"307","district_id"=>"60","name"=>"Kumarkhali","bn_name"=>"কুমারখালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"308","district_id"=>"60","name"=>"Daulatpur","bn_name"=>"দৌলতপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"309","district_id"=>"60","name"=>"Mirpur","bn_name"=>"মিরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"310","district_id"=>"60","name"=>"Bheramara","bn_name"=>"ভেরামারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"311","district_id"=>"60","name"=>"Khoksa","bn_name"=>"খোকসা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"312","district_id"=>"61","name"=>"Magura Sadar ","bn_name"=>"মাগুরা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"313","district_id"=>"61","name"=>"Mohammadpur ","bn_name"=>"মোহাম্মাদপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"314","district_id"=>"61","name"=>"Shalikha ","bn_name"=>"শালিখা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"315","district_id"=>"61","name"=>"Sreepur ","bn_name"=>"শ্রীপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"316","district_id"=>"62","name"=>"angni ","bn_name"=>"আংনি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"317","district_id"=>"62","name"=>"Mujib Nagar ","bn_name"=>"মুজিব নগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"318","district_id"=>"62","name"=>"Meherpur-S ","bn_name"=>"মেহেরপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"319","district_id"=>"63","name"=>"Narail-S Upazilla","bn_name"=>"নড়াইল সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"320","district_id"=>"63","name"=>"Lohagara Upazilla","bn_name"=>"লোহাগাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"321","district_id"=>"63","name"=>"Kalia Upazilla","bn_name"=>"কালিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"322","district_id"=>"64","name"=>"Satkhira Sadar ","bn_name"=>"সাতক্ষীরা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"323","district_id"=>"64","name"=>"Assasuni ","bn_name"=>"আসসাশুনি ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"324","district_id"=>"64","name"=>"Debhata ","bn_name"=>"দেভাটা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"325","district_id"=>"64","name"=>"Tala ","bn_name"=>"তালা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"326","district_id"=>"64","name"=>"Kalaroa ","bn_name"=>"কলরোয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"327","district_id"=>"64","name"=>"Kaliganj ","bn_name"=>"কালীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"328","district_id"=>"64","name"=>"Shyamnagar ","bn_name"=>"শ্যামনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"329","district_id"=>"18","name"=>"Adamdighi","bn_name"=>"আদমদিঘী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"330","district_id"=>"18","name"=>"Bogra Sadar","bn_name"=>"বগুড়া সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"331","district_id"=>"18","name"=>"Sherpur","bn_name"=>"শেরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"332","district_id"=>"18","name"=>"Dhunat","bn_name"=>"ধুনট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"333","district_id"=>"18","name"=>"Dhupchanchia","bn_name"=>"দুপচাচিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"334","district_id"=>"18","name"=>"Gabtali","bn_name"=>"গাবতলি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"335","district_id"=>"18","name"=>"Kahaloo","bn_name"=>"কাহালু","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"336","district_id"=>"18","name"=>"Nandigram","bn_name"=>"নন্দিগ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"337","district_id"=>"18","name"=>"Sahajanpur","bn_name"=>"শাহজাহানপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"338","district_id"=>"18","name"=>"Sariakandi","bn_name"=>"সারিয়াকান্দি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"339","district_id"=>"18","name"=>"Shibganj","bn_name"=>"শিবগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"340","district_id"=>"18","name"=>"Sonatala","bn_name"=>"সোনাতলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"341","district_id"=>"19","name"=>"Joypurhat S","bn_name"=>"জয়পুরহাট সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"342","district_id"=>"19","name"=>"Akkelpur","bn_name"=>"আক্কেলপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"343","district_id"=>"19","name"=>"Kalai","bn_name"=>"কালাই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"344","district_id"=>"19","name"=>"Khetlal","bn_name"=>"খেতলাল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"345","district_id"=>"19","name"=>"Panchbibi","bn_name"=>"পাঁচবিবি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"346","district_id"=>"20","name"=>"Naogaon Sadar ","bn_name"=>"নওগাঁ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"347","district_id"=>"20","name"=>"Mohadevpur ","bn_name"=>"মহাদেবপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"348","district_id"=>"20","name"=>"Manda ","bn_name"=>"মান্দা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"349","district_id"=>"20","name"=>"Niamatpur ","bn_name"=>"নিয়ামতপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"350","district_id"=>"20","name"=>"Atrai ","bn_name"=>"আত্রাই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"351","district_id"=>"20","name"=>"Raninagar ","bn_name"=>"রাণীনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"352","district_id"=>"20","name"=>"Patnitala ","bn_name"=>"পত্নীতলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"353","district_id"=>"20","name"=>"Dhamoirhat ","bn_name"=>"ধামইরহাট ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"354","district_id"=>"20","name"=>"Sapahar ","bn_name"=>"সাপাহার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"355","district_id"=>"20","name"=>"Porsha ","bn_name"=>"পোরশা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"356","district_id"=>"20","name"=>"Badalgachhi ","bn_name"=>"বদলগাছি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"357","district_id"=>"21","name"=>"Natore Sadar ","bn_name"=>"নাটোর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"358","district_id"=>"21","name"=>"Baraigram ","bn_name"=>"বড়াইগ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"359","district_id"=>"21","name"=>"Bagatipara ","bn_name"=>"বাগাতিপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"360","district_id"=>"21","name"=>"Lalpur ","bn_name"=>"লালপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"361","district_id"=>"21","name"=>"Natore Sadar ","bn_name"=>"নাটোর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"362","district_id"=>"21","name"=>"Baraigram ","bn_name"=>"বড়াই গ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"363","district_id"=>"22","name"=>"Bholahat ","bn_name"=>"ভোলাহাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"364","district_id"=>"22","name"=>"Gomastapur ","bn_name"=>"গোমস্তাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"365","district_id"=>"22","name"=>"Nachole ","bn_name"=>"নাচোল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"366","district_id"=>"22","name"=>"Nawabganj Sadar ","bn_name"=>"নবাবগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"367","district_id"=>"22","name"=>"Shibganj ","bn_name"=>"শিবগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"368","district_id"=>"23","name"=>"Atgharia ","bn_name"=>"আটঘরিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"369","district_id"=>"23","name"=>"Bera ","bn_name"=>"বেড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"370","district_id"=>"23","name"=>"Bhangura ","bn_name"=>"ভাঙ্গুরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"371","district_id"=>"23","name"=>"Chatmohar ","bn_name"=>"চাটমোহর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"372","district_id"=>"23","name"=>"Faridpur ","bn_name"=>"ফরিদপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"373","district_id"=>"23","name"=>"Ishwardi ","bn_name"=>"ঈশ্বরদী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"374","district_id"=>"23","name"=>"Pabna Sadar ","bn_name"=>"পাবনা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"375","district_id"=>"23","name"=>"Santhia ","bn_name"=>"সাথিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"376","district_id"=>"23","name"=>"Sujanagar ","bn_name"=>"সুজানগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"377","district_id"=>"24","name"=>"Bagha","bn_name"=>"বাঘা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"378","district_id"=>"24","name"=>"Bagmara","bn_name"=>"বাগমারা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"379","district_id"=>"24","name"=>"Charghat","bn_name"=>"চারঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"380","district_id"=>"24","name"=>"Durgapur","bn_name"=>"দুর্গাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"381","district_id"=>"24","name"=>"Godagari","bn_name"=>"গোদাগারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"382","district_id"=>"24","name"=>"Mohanpur","bn_name"=>"মোহনপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"383","district_id"=>"24","name"=>"Paba","bn_name"=>"পবা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"384","district_id"=>"24","name"=>"Puthia","bn_name"=>"পুঠিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"385","district_id"=>"24","name"=>"Tanore","bn_name"=>"তানোর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"386","district_id"=>"25","name"=>"Sirajganj Sadar ","bn_name"=>"সিরাজগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"387","district_id"=>"25","name"=>"Belkuchi ","bn_name"=>"বেলকুচি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"388","district_id"=>"25","name"=>"Chauhali ","bn_name"=>"চৌহালি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"389","district_id"=>"25","name"=>"Kamarkhanda ","bn_name"=>"কামারখান্দা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"390","district_id"=>"25","name"=>"Kazipur ","bn_name"=>"কাজীপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"391","district_id"=>"25","name"=>"Raiganj ","bn_name"=>"রায়গঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"392","district_id"=>"25","name"=>"Shahjadpur ","bn_name"=>"শাহজাদপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"393","district_id"=>"25","name"=>"Tarash ","bn_name"=>"তারাশ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"394","district_id"=>"25","name"=>"Ullahpara ","bn_name"=>"উল্লাপাড়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"395","district_id"=>"26","name"=>"Birampur ","bn_name"=>"বিরামপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"396","district_id"=>"26","name"=>"Birganj","bn_name"=>"বীরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"397","district_id"=>"26","name"=>"Biral ","bn_name"=>"বিড়াল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"398","district_id"=>"26","name"=>"Bochaganj ","bn_name"=>"বোচাগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"399","district_id"=>"26","name"=>"Chirirbandar ","bn_name"=>"চিরিরবন্দর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"400","district_id"=>"26","name"=>"Phulbari ","bn_name"=>"ফুলবাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"401","district_id"=>"26","name"=>"Ghoraghat ","bn_name"=>"ঘোড়াঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"402","district_id"=>"26","name"=>"Hakimpur ","bn_name"=>"হাকিমপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"403","district_id"=>"26","name"=>"Kaharole ","bn_name"=>"কাহারোল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"404","district_id"=>"26","name"=>"Khansama ","bn_name"=>"খানসামা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"405","district_id"=>"26","name"=>"Dinajpur Sadar ","bn_name"=>"দিনাজপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"406","district_id"=>"26","name"=>"Nawabganj","bn_name"=>"নবাবগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"407","district_id"=>"26","name"=>"Parbatipur ","bn_name"=>"পার্বতীপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"408","district_id"=>"27","name"=>"Fulchhari","bn_name"=>"ফুলছড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"409","district_id"=>"27","name"=>"Gaibandha sadar","bn_name"=>"গাইবান্ধা সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"410","district_id"=>"27","name"=>"Gobindaganj","bn_name"=>"গোবিন্দগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"411","district_id"=>"27","name"=>"Palashbari","bn_name"=>"পলাশবাড়ী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"412","district_id"=>"27","name"=>"Sadullapur","bn_name"=>"সাদুল্যাপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"413","district_id"=>"27","name"=>"Saghata","bn_name"=>"সাঘাটা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"414","district_id"=>"27","name"=>"Sundarganj","bn_name"=>"সুন্দরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"415","district_id"=>"28","name"=>"Kurigram Sadar","bn_name"=>"কুড়িগ্রাম সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"416","district_id"=>"28","name"=>"Nageshwari","bn_name"=>"নাগেশ্বরী","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"417","district_id"=>"28","name"=>"Bhurungamari","bn_name"=>"ভুরুঙ্গামারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"418","district_id"=>"28","name"=>"Phulbari","bn_name"=>"ফুলবাড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"419","district_id"=>"28","name"=>"Rajarhat","bn_name"=>"রাজারহাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"420","district_id"=>"28","name"=>"Ulipur","bn_name"=>"উলিপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"421","district_id"=>"28","name"=>"Chilmari","bn_name"=>"চিলমারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"422","district_id"=>"28","name"=>"Rowmari","bn_name"=>"রউমারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"423","district_id"=>"28","name"=>"Char Rajibpur","bn_name"=>"চর রাজিবপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"424","district_id"=>"29","name"=>"Lalmanirhat Sadar","bn_name"=>"লালমনিরহাট সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"425","district_id"=>"29","name"=>"Aditmari","bn_name"=>"আদিতমারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"426","district_id"=>"29","name"=>"Kaliganj","bn_name"=>"কালীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"427","district_id"=>"29","name"=>"Hatibandha","bn_name"=>"হাতিবান্ধা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"428","district_id"=>"29","name"=>"Patgram","bn_name"=>"পাটগ্রাম","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"429","district_id"=>"30","name"=>"Nilphamari Sadar","bn_name"=>"নীলফামারী সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"430","district_id"=>"30","name"=>"Saidpur","bn_name"=>"সৈয়দপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"431","district_id"=>"30","name"=>"Jaldhaka","bn_name"=>"জলঢাকা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"432","district_id"=>"30","name"=>"Kishoreganj","bn_name"=>"কিশোরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"433","district_id"=>"30","name"=>"Domar","bn_name"=>"ডোমার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"434","district_id"=>"30","name"=>"Dimla","bn_name"=>"ডিমলা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"435","district_id"=>"31","name"=>"Panchagarh Sadar","bn_name"=>"পঞ্চগড় সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"436","district_id"=>"31","name"=>"Debiganj","bn_name"=>"দেবীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"437","district_id"=>"31","name"=>"Boda","bn_name"=>"বোদা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"438","district_id"=>"31","name"=>"Atwari","bn_name"=>"আটোয়ারি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"439","district_id"=>"31","name"=>"Tetulia","bn_name"=>"তেতুলিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"440","district_id"=>"32","name"=>"Badarganj","bn_name"=>"বদরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"441","district_id"=>"32","name"=>"Mithapukur","bn_name"=>"মিঠাপুকুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"442","district_id"=>"32","name"=>"Gangachara","bn_name"=>"গঙ্গাচরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"443","district_id"=>"32","name"=>"Kaunia","bn_name"=>"কাউনিয়া","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"444","district_id"=>"32","name"=>"Rangpur Sadar","bn_name"=>"রংপুর সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"445","district_id"=>"32","name"=>"Pirgachha","bn_name"=>"পীরগাছা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"446","district_id"=>"32","name"=>"Pirganj","bn_name"=>"পীরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"447","district_id"=>"32","name"=>"Taraganj","bn_name"=>"তারাগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"448","district_id"=>"33","name"=>"Thakurgaon Sadar ","bn_name"=>"ঠাকুরগাঁও সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"449","district_id"=>"33","name"=>"Pirganj ","bn_name"=>"পীরগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"450","district_id"=>"33","name"=>"Baliadangi ","bn_name"=>"বালিয়াডাঙ্গি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"451","district_id"=>"33","name"=>"Haripur ","bn_name"=>"হরিপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"452","district_id"=>"33","name"=>"Ranisankail ","bn_name"=>"রাণীসংকইল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"453","district_id"=>"51","name"=>"Ajmiriganj","bn_name"=>"আজমিরিগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"454","district_id"=>"51","name"=>"Baniachang","bn_name"=>"বানিয়াচং","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"455","district_id"=>"51","name"=>"Bahubal","bn_name"=>"বাহুবল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"456","district_id"=>"51","name"=>"Chunarughat","bn_name"=>"চুনারুঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"457","district_id"=>"51","name"=>"Habiganj Sadar","bn_name"=>"হবিগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"458","district_id"=>"51","name"=>"Lakhai","bn_name"=>"লাক্ষাই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"459","district_id"=>"51","name"=>"Madhabpur","bn_name"=>"মাধবপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"460","district_id"=>"51","name"=>"Nabiganj","bn_name"=>"নবীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"461","district_id"=>"51","name"=>"Shaistagonj ","bn_name"=>"শায়েস্তাগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"462","district_id"=>"52","name"=>"Moulvibazar Sadar","bn_name"=>"মৌলভীবাজার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"463","district_id"=>"52","name"=>"Barlekha","bn_name"=>"বড়লেখা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"464","district_id"=>"52","name"=>"Juri","bn_name"=>"জুড়ি","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"465","district_id"=>"52","name"=>"Kamalganj","bn_name"=>"কামালগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"466","district_id"=>"52","name"=>"Kulaura","bn_name"=>"কুলাউরা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"467","district_id"=>"52","name"=>"Rajnagar","bn_name"=>"রাজনগর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"468","district_id"=>"52","name"=>"Sreemangal","bn_name"=>"শ্রীমঙ্গল","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"469","district_id"=>"53","name"=>"Bishwamvarpur","bn_name"=>"বিসশম্ভারপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"470","district_id"=>"53","name"=>"Chhatak","bn_name"=>"ছাতক","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"471","district_id"=>"53","name"=>"Derai","bn_name"=>"দেড়াই","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"472","district_id"=>"53","name"=>"Dharampasha","bn_name"=>"ধরমপাশা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"473","district_id"=>"53","name"=>"Dowarabazar","bn_name"=>"দোয়ারাবাজার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"474","district_id"=>"53","name"=>"Jagannathpur","bn_name"=>"জগন্নাথপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"475","district_id"=>"53","name"=>"Jamalganj","bn_name"=>"জামালগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"476","district_id"=>"53","name"=>"Sulla","bn_name"=>"সুল্লা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"477","district_id"=>"53","name"=>"Sunamganj Sadar","bn_name"=>"সুনামগঞ্জ সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"478","district_id"=>"53","name"=>"Shanthiganj","bn_name"=>"শান্তিগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"479","district_id"=>"53","name"=>"Tahirpur","bn_name"=>"তাহিরপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"480","district_id"=>"54","name"=>"Sylhet Sadar","bn_name"=>"সিলেট সদর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"481","district_id"=>"54","name"=>"Beanibazar","bn_name"=>"বেয়ানিবাজার","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"482","district_id"=>"54","name"=>"Bishwanath","bn_name"=>"বিশ্বনাথ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"483","district_id"=>"54","name"=>"Dakshin Surma ","bn_name"=>"দক্ষিণ সুরমা","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"484","district_id"=>"54","name"=>"Balaganj","bn_name"=>"বালাগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"485","district_id"=>"54","name"=>"Companiganj","bn_name"=>"কোম্পানিগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"486","district_id"=>"54","name"=>"Fenchuganj","bn_name"=>"ফেঞ্চুগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"487","district_id"=>"54","name"=>"Golapganj","bn_name"=>"গোলাপগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"488","district_id"=>"54","name"=>"Gowainghat","bn_name"=>"গোয়াইনঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"489","district_id"=>"54","name"=>"Jaintiapur","bn_name"=>"জয়ন্তপুর","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"490","district_id"=>"54","name"=>"Kanaighat","bn_name"=>"কানাইঘাট","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"491","district_id"=>"54","name"=>"Zakiganj","bn_name"=>"জাকিগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"492","district_id"=>"54","name"=>"Nobigonj","bn_name"=>"নবীগঞ্জ","lat"=>"0","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"493","district_id"=>"1","name"=>"Adabor","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"494","district_id"=>"1","name"=>"Airport","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"495","district_id"=>"1","name"=>"Badda","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"496","district_id"=>"1","name"=>"Banani","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"497","district_id"=>"1","name"=>"Bangshal","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"498","district_id"=>"1","name"=>"Bhashantek","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"499","district_id"=>"1","name"=>"Cantonment","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"500","district_id"=>"1","name"=>"Chackbazar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"501","district_id"=>"1","name"=>"Darussalam","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"502","district_id"=>"1","name"=>"Daskhinkhan","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"503","district_id"=>"1","name"=>"Demra","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"504","district_id"=>"1","name"=>"Dhamrai","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"505","district_id"=>"1","name"=>"Dhanmondi","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"506","district_id"=>"1","name"=>"Dohar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"507","district_id"=>"1","name"=>"Gandaria","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"508","district_id"=>"1","name"=>"Gulshan","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"509","district_id"=>"1","name"=>"Hazaribag","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"510","district_id"=>"1","name"=>"Jatrabari","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"511","district_id"=>"1","name"=>"Kafrul","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"512","district_id"=>"1","name"=>"Kalabagan","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"513","district_id"=>"1","name"=>"Kamrangirchar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"514","district_id"=>"1","name"=>"Keraniganj","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"515","district_id"=>"1","name"=>"Khilgaon","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"516","district_id"=>"1","name"=>"Khilkhet","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"517","district_id"=>"1","name"=>"Kotwali","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"518","district_id"=>"1","name"=>"Lalbag","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"519","district_id"=>"1","name"=>"Mirpur Model","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"520","district_id"=>"1","name"=>"Mohammadpur","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"521","district_id"=>"1","name"=>"Motijheel","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"522","district_id"=>"1","name"=>"Mugda","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"523","district_id"=>"1","name"=>"Nawabganj","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"524","district_id"=>"1","name"=>"New Market","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"525","district_id"=>"1","name"=>"Pallabi","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"526","district_id"=>"1","name"=>"Paltan","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"527","district_id"=>"1","name"=>"Ramna","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"528","district_id"=>"1","name"=>"Rampura","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"529","district_id"=>"1","name"=>"Rupnagar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"530","district_id"=>"1","name"=>"Sabujbag","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"531","district_id"=>"1","name"=>"Savar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"532","district_id"=>"1","name"=>"Shah Ali","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"533","district_id"=>"1","name"=>"Shahbag","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"534","district_id"=>"1","name"=>"Shahjahanpur","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"535","district_id"=>"1","name"=>"Sherebanglanagar","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"536","district_id"=>"1","name"=>"Shyampur","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"537","district_id"=>"1","name"=>"Sutrapur","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"538","district_id"=>"1","name"=>"Tejgaon","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"539","district_id"=>"1","name"=>"Tejgaon I\/A","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"540","district_id"=>"1","name"=>"Turag","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"541","district_id"=>"1","name"=>"Uttara","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"542","district_id"=>"1","name"=>"Uttara West","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"543","district_id"=>"1","name"=>"Uttarkhan","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"544","district_id"=>"1","name"=>"Vatara","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"545","district_id"=>"1","name"=>"Wari","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"546","district_id"=>"1","name"=>"Others","bn_name"=>null,"lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"547","district_id"=>"35","name"=>"Airport","bn_name"=>"এয়ারপোর্ট","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"548","district_id"=>"35","name"=>"Kawnia","bn_name"=>"কাউনিয়া","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"549","district_id"=>"35","name"=>"Bondor","bn_name"=>"বন্দর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"550","district_id"=>"35","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"551","district_id"=>"24","name"=>"Boalia","bn_name"=>"বোয়ালিয়া","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"552","district_id"=>"24","name"=>"Motihar","bn_name"=>"মতিহার","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"553","district_id"=>"24","name"=>"Shahmokhdum","bn_name"=>"শাহ্ মকখদুম ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"554","district_id"=>"24","name"=>"Rajpara","bn_name"=>"রাজপারা ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"555","district_id"=>"24","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"556","district_id"=>"43","name"=>"Akborsha","bn_name"=>"Akborsha","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"557","district_id"=>"43","name"=>"Baijid bostami","bn_name"=>"বাইজিদ বোস্তামী","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"558","district_id"=>"43","name"=>"Bakolia","bn_name"=>"বাকোলিয়া","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"559","district_id"=>"43","name"=>"Bandar","bn_name"=>"বন্দর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"560","district_id"=>"43","name"=>"Chandgaon","bn_name"=>"চাঁদগাও","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"561","district_id"=>"43","name"=>"Chokbazar","bn_name"=>"চকবাজার","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"562","district_id"=>"43","name"=>"Doublemooring","bn_name"=>"ডাবল মুরিং","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"563","district_id"=>"43","name"=>"EPZ","bn_name"=>"ইপিজেড","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"564","district_id"=>"43","name"=>"Hali Shohor","bn_name"=>"হলী শহর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"565","district_id"=>"43","name"=>"Kornafuli","bn_name"=>"কর্ণফুলি","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"566","district_id"=>"43","name"=>"Kotwali","bn_name"=>"কোতোয়ালী","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"567","district_id"=>"43","name"=>"Kulshi","bn_name"=>"কুলশি","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"568","district_id"=>"43","name"=>"Pahartali","bn_name"=>"পাহাড়তলী","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"569","district_id"=>"43","name"=>"Panchlaish","bn_name"=>"পাঁচলাইশ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"570","district_id"=>"43","name"=>"Potenga","bn_name"=>"পতেঙ্গা","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"571","district_id"=>"43","name"=>"Shodhorgat","bn_name"=>"সদরঘাট","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"572","district_id"=>"43","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"573","district_id"=>"44","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"574","district_id"=>"59","name"=>"Aranghata","bn_name"=>"আড়াংঘাটা","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"575","district_id"=>"59","name"=>"Daulatpur","bn_name"=>"দৌলতপুর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"576","district_id"=>"59","name"=>"Harintana","bn_name"=>"হারিন্তানা ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"577","district_id"=>"59","name"=>"Horintana","bn_name"=>"হরিণতানা ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"578","district_id"=>"59","name"=>"Khalishpur","bn_name"=>"খালিশপুর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"579","district_id"=>"59","name"=>"Khanjahan Ali","bn_name"=>"খানজাহান আলী","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"580","district_id"=>"59","name"=>"Khulna Sadar","bn_name"=>"খুলনা সদর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"581","district_id"=>"59","name"=>"Labanchora","bn_name"=>"লাবানছোরা","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"582","district_id"=>"59","name"=>"Sonadanga","bn_name"=>"সোনাডাঙ্গা","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"583","district_id"=>"59","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"584","district_id"=>"2","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"585","district_id"=>"4","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"586","district_id"=>"5","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"587","district_id"=>"54","name"=>"Airport","bn_name"=>"বিমানবন্দর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"588","district_id"=>"54","name"=>"Hazrat Shah Paran","bn_name"=>"হযরত শাহ পরাণ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"589","district_id"=>"54","name"=>"Jalalabad","bn_name"=>"জালালাবাদ","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"590","district_id"=>"54","name"=>"Kowtali","bn_name"=>"কোতোয়ালী","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"591","district_id"=>"54","name"=>"Moglabazar","bn_name"=>"মোগলাবাজার","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"592","district_id"=>"54","name"=>"Osmani Nagar","bn_name"=>"ওসমানী নগর","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"593","district_id"=>"54","name"=>"South Surma","bn_name"=>"দক্ষিণ সুরমা","lat"=>"2016","long"=>"0","status"=>"Active"]);
            Policestation::create(["id"=>"594","district_id"=>"54","name"=>"Others","bn_name"=>"অন্যান্য","lat"=>"2016","long"=>"0","status"=>"Active"]);
}
}
